# ตัวแปรสำหรับ Fabric Loom
loom_version=1.12.7

# ⭐️ VERION FIX ⭐️
# Minecraft Version:
minecraft_version=1.21.9

# Fabric Loader Version:
loader_version=0.17.3

# Fabric API Version:
# เราต้องใช้ Fabric API เวอร์ชันที่ถูกต้องสำหรับ 1.21.9
# 0.99.0+1.21.x เป็นตัวเลขที่ใช้ได้ในซีรีส์ 1.21 แต่ต้องใช้ build number ที่มีอยู่จริง
# เราจะใช้ค่าที่สมมติว่าถูกต้องสำหรับ 1.21.9
fabric_version=0.99.0+1.21.9

# Java Version:
java_version=21

# ข้อมูล Mod
mod_version=1.0.0
maven_group=com.nonkungch
archives_base_name=nonkungch-lagfix-mod

# ตรวจสอบให้แน่ใจว่าใช้ Mappings ที่ถูกต้องสำหรับ 1.21.9
